### ISSUE TITLE
Title object is missing on notifications when commenting wall

### ISSUE THREAD

**Issue by nlybe** [hypeJunction/hypeNotifications#1]
Hi Ismayl. You made great work on this notification plugin. Thanks for sharing.

There is a small issue, which I am not sure that is due to this plugin. When commend a wall message, the object title is missing from notification:
You have a new comment on your item "" from USER. It reads: 
.....

![1](https://cloud.githubusercontent.com/assets/4714025/23821485/8a89c44c-063c-11e7-91b6-fa2604d10a00.png)

**Comment by hypeJunction** [comment]
I will need to see what's up

**Comment by hypeJunction** [comment]
It's an Elgg issue, so open a ticket there.
