### ISSUE TITLE
How to adjust language in friend request email that is sent?

### ISSUE THREAD

**Issue by javery86** [hypeJunction/hypeNotifications#12]
I would like to adjust the language below that is sent to a user when they receive a friend request. And more specifically, the URL is right next to the colon with no space so it's not being recognized as a clickable link in the email message. How would I go about changing/fixing that?

"Admin wants to be your friend! But they are waiting for you to approve the
request...so login now so you can approve the request!

You can view your pending friend requests
at:https://URL.com/friend_request/USERNAME

Make sure you are logged into the website before clicking on the following
link otherwise you will be redirected to the login page.

(You cannot reply to this email.)"

**Comment by hypeJunction** [comment]
See friend request plugins language files.
