### ISSUE TITLE
Notification settings aren't taking effect after being saved

### ISSUE THREAD

**Issue by javery86** [hypeJunction/hypeNotifications#14]
After saving a user's notification settings in the profile, those settings aren't actually taking effect. For example, either receiving site notifications or email notifications still isn't taking effect after saving with both those settings "turned on".

**Comment by hypeJunction** [comment]
Do you have your cron job for one minute setup?

**Comment by javery86** [comment]
No I do not.

Joseph Avery, MSc, ACSM-RCEP
Phone: (808) 853-0675
Email: j.avery@msn.com<mailto:j.avery@msn.com>

On Dec 18, 2017, at 2:08 AM, Ismayil Khayredinov <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you have your cron job for one minute setup?

**Comment by hypeJunction** [comment]
Read Elgg core documentation about notifications and cron.
