### ISSUE TITLE
Image bleeding with text on html email notifications

### ISSUE THREAD

**Issue by dploeger** [hypeJunction/hypeNotifications#17]
On HTML e-mail notifications, the user icon is bleeding with the text.

**Comment by hypeJunction** [comment]
Could you post raw email, if you can?
It is using the styles from your theme, so it's possible you need to alter something there

**Comment by dploeger** [comment]
Hm. I'm using HypeUI. But just realized, that I was using a kinda old version, so I'll check again with the current one. I'll reopen this, if the problem persists.
