### ISSUE TITLE
use default elgg way of pointing notifications directly to entities?

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeNotifications#2]
i was surprised when i tested this plugin in 2.3 that when notifications appear in the notifier, their target URL points to a new type of notification page that displays each individual notification on its own page.
is there a way i am missing to disable this design and just have the links in the notifier work as they do in default elgg (and facebook)?

**Comment by propertunist** [comment]
another related issue is that there is an undocumented dependency on hypeInteractions when viewing comments. if i do not have hypeInteractions activated then when i click to view a comment that is part of a 'stream' then i get a 404 page not found.

**Comment by hypeJunction** [comment]
It uses URLs when there is an object. For some instant notifications it can't determine that - I added a PR into core that rectifies that in master. Notifier had some own hooks and was second guessing URLs, which was causing issues with other plugins, so I didn't want to do that. 
I don't think there are any dependencies on hypeIntetactions, it just uses the notification that core is being sent, but I will check

**Comment by hypeJunction** [comment]
FYI, URLs are not dynamic, so if you received a notification when a plugin was active, and then you disabled it, it won't update the URLs. It's basically similar to receiving an email. There is plenty of ways to assign URLs dynamically, but it's an unthankful job of mapping 200 notification types to their object URLs.

**Comment by propertunist** [comment]
ok, yes, i understand your 2nd comment here. i don't expect the urls to be updated historically or if the plugin involved is missing. 
i can see in your code that the following language key structures are looked for:
```
			"notification:summary:$action:$object_type:$object_subtype",
			"notification:summary:$action:$object_type:default",
			"notification:summary:$action:default",
```
when i search my entire mod folder i cannot find more than a couple of keys that match the initial structure across all my plugins. videolist, for example, is one where no matches come up, but i do see a similar key with the format: videolist:notification:summary
i am not sure if i need to change that to: notification:summary:create:object:videolist
is that correct?

the issue with hypeinteractions appears to me to be a genuine bug because i never activated hypeInteractions on my test server and yet i saw that problem.
to recreate:
1. activate hypeNotifications on an elgg site that never ran hypeInteractions previously.
2. add an entity (in my example i used a tidypics photo, but i think this applies to other types too).
3. comment on the entity
3. another user comments on the entity.
4. the original user sees the notification of the other user's comment and the URL of the notification is of the format: http://mysite.org/stream/comments/1336/1342?active_tab=comments#elgg-object-1342

**Comment by hypeJunction** [comment]
If you want a pretty summary, you can add the language keys. Unfortunately, not all plugins add the summary to the notification.

**Comment by hypeJunction** [comment]
I don't see where the stream URL is coming from. Definitely not hypeNotifications.

**Comment by propertunist** [comment]
i am looking more closely at what might be done to improve the content of the notifications and am seeing something i don't understand. even for the default blog plugin, the notification objects that are being used in your notification class do not have their action, object or subtype set.

i traced the process through to the function  'sendNotification'  in the siteNotificationService.php file. In there you are using an event object and passing through various parameters to a notification object, but for some reason you aren't passing through the object type, action and subtype. 
I added these two lines to siteNotificationService.php:
```
			$site_notification->setAction($event->getAction());
			$site_notification->setObject($event->getObject() ?: null);
```
within the function sendNotification in the else part of the if statement that begins:
```
if (!$event instanceof NotificationEvent) {
```
i then also changed the line that handles the subtype variable in the function getSummary in the Notifications.php file to be:
```
$object_subtype = get_subtype_from_id($this->object_subtype);
```
this results in a usable language key being generated when i write a comment on a blog, for example. however, the problem now is that the object subtype is 'comment' and there is no subtype available for the object that is being acted on.
i'm tired now and will come back to this tomorrow, but i think this maybe relates back to what you wrote about URLs being second guessed? but i have no idea why it is a problem for a notification's real object to be accessed in code..

**Comment by hypeJunction** [comment]
I think I did fix the problem with the object not being set correctly in master. Are copying this code from your copy?

**Comment by propertunist** [comment]
i don't understand your question here... can you write that a different way?

**Comment by propertunist** [comment]
oh, you were asking if i was using my own version of your code and not the master version? i was using the release, not the master. i'll test the master now

**Comment by propertunist** [comment]
you are right, yes - the master has resolved that issue. so now i have added a language string for comments into the en.php language file:
```
'notification:summary:create:object:comment' => '%s commented on %s'
```
and that works - although the format of the link for the entity is just the raw url. there is still the need to bring in the subtype of the target entity and maybe the title of the target entity somehow.

**Comment by hypeJunction** [comment]
Use the hooks to alter the notifiation's body/title/summary for `site` method. There are so many pitfalls here, it's like opening a pandora box.
