### ISSUE TITLE
notification strings missing after upgrade

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeNotifications#4]
i just upgraded my main site to 2.3 elgg and ran the hypeNotifications upgrade script. i can see numerous entries in the notifications list for my user where there is just a language string, with nothing else. e.g:
river:create:object:thewire

thewire was never disabled during the upgrade processing, so that isn't the cause.

**Comment by hypeJunction** [comment]
You are probably seeing the summary that never had a translation in notifier: https://github.com/hypeJunction/hypeNotifications/blob/master/actions/upgrade/notifications/notifier.php#L71

**Comment by propertunist** [comment]
i'm not sure what you mean there. the string is just a standard one from thewire which was never a problem when it was rendered by notifier. examples of other strings that are similarly not being rendered properly are:
river:create:object:videolist_item
river:comment:object:blog

**Comment by hypeJunction** [comment]
hypeNotifiation does not use those strings, they are coming from somewhere else. I suppose you could double wrap the notification summary in elgg_echo().

**Comment by hypeJunction** [comment]
It's not an upgrade, it's a migration script. Feel free to improve it, but I am not going to invest any more time into it.
