### ISSUE TITLE
missing notifications in the 'all notifications' view

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeNotifications#5]
on my live site, if i view: /notifications/all
i see only 11 notifications for me. is that correct? shouldn't there be a way to view the full history of notifications on that page?

**Comment by propertunist** [comment]
so i checked this for a non-admin user and i see the pagination for that user. so it looks like the problem is not pagination, but that most of the notifications for my admin user are missing.

**Comment by hypeJunction** [comment]
I am not going to debug any of the notifier issues. The migration script worked as it should on the production site that this plugin was originally intended for. I don't really care for past notifications, their life span is so short that I'd rather wipe all the old ones and start fresh.
