### ISSUE TITLE
users incorrectly routed to notifications/ticker on login

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeNotifications#6]
more than 50% of the time that i login to my production site, i am being routed to mysite.org/notifications/ticker and so see a 404 not found error.
i am guessing that this might be some kind of timing error with the ajax call to the ticker, but i am only seeing it on the initial login and not on subsequent page loads.

**Comment by propertunist** [comment]
i appear to have fixed this by delaying the call to the ticker function in popup.js until the page has loaded:
```
	jQuery(document).ready(function($)
	{
		ticker();
	});
```

**Comment by hypeJunction** [comment]
It shouldn't really be ticking for logged out users. Will look into it next week

**Comment by propertunist** [comment]
the issue only occurs once i am logged in, on the initial load of the first page - as far as i am aware.

**Comment by propertunist** [comment]
or maybe during the login action somehow.. i am not familiar with how all of these events are scheduled internally to elgg core.

**Comment by hypeJunction** [comment]
Elgg stores destination URL before the login form is shown, so when an AJAX call is made it just replaced that. There are a few tickets about it on github

**Comment by propertunist** [comment]
looks like my code change didn't fix this issue as i have just seen it happen again

**Comment by propertunist** [comment]
the new release appears to have fixed this correctly- thanks

**Comment by propertunist** [comment]
i just saw this again on my live site

**Comment by hypeJunction** [comment]
Don't know.

**Comment by hypeJunction** [comment]
This issue needs to be solved in core: https://github.com/Elgg/Elgg/issues/10695
